const semesterSubjects = {
    Semester_1: {
      DSC: [
        "Computer Fundamental",
        "Mathematics For Computing-1",
        "Programming Using Python",
      ],
      AEC: ["Environment Science Section-7"],
      VAC: [
        "Ethics and Culture",
        "Culture and Communication",
        "Constitution Rights",
        "Science and Society",
      ],
      SEC: [
        "Frontend Web Design and Development",
        "Personal Finance Planning",
        "Cloud Computing",
      ],
      GE: ["Programming Using C++", "Basic Statistics", "Cloud Computing"],
    },
    Semester_2: {
      DSC: [
        "Database Management Systems",
        "Programming in JAVA",
        "Mathematics for Computing - II",
      ],
      AEC: [
        "Hindi A - Section 1",
        "Hindi A - Section 2",
        "Hindi A - Section 3",
        "Hindi B - Section 1",
        "Hindi B - Section 2",
        "Hindi B - Section 3",
        "Hindi B - Section 4",
        "Hindi B - Section 5",
        "Hindi B - Section 6",
        "Hindi C - Section 1",
        "Hindi D - Section 1 (For Foreign students)",
        "Hindi E - Section 1",
        "Environmental Science – Section 1",
        "Environmental Science – Section 2",
        "Environmental Science – Section 3",
        "Environmental Science – Section 4",
        "Environmental Science – Section 5",
        "Environmental Science – Section 6",
        "Environmental Science – Section 7",
        "Environmental Science – Section 8",
        "Environmental Science – Section 9",
        "Environmental Science – Section 10",
        "Indian Language (Punjabi 1)",
        "Indian Language (Punjabi 2)"
      ],
      VAC: [
        "Financial Literacy",
        "Digital Empowerment",
        "Art of Being Happy",
        "Social and Emotional Learning",
        "Gandhi and Education",
        "Ecology and Literature",
        "Science and Society",
        "Ethics and Culture",
        "Fit India",
        "National Cadet Corps-I"
      ],
      SEC: [
        "Finance For Everyone",
        "Basic IT Tools",
        "Environmental Accounting",
        "Document Preparation & Presentation Software",
        "IT Skills and Data Analysis – I",
        "Communication in Everyday Life",
        "Creative Writing",
        "Negotiation and Leadership",
        "Rangmanch (Theatre)",
        "Sustainable Ecotourism and Entrepreneurship",
        "IT Skills and Data Analysis - II",
        "Personal Financial Planning",
        "Business Intelligence and Data Visualization",
        "Introduction to Blockchain",
        "Early Child Care and Educational Settings",
        "Museum and Museology",
        "Yoga in Practice"
      ],
      GE: [
        "Financial Management for Beginners",
        "Communication in Management",
        "Principles of Macroeconomics I",
        "Critical Thinking",
        "Introduction to Linear Algebra",
        "Individual and Society",
        "Basics of Social Psychology",
        "Delhi through the Ages: From Colonial to Contemporary Times",
        "Introduction to International Business",
        "Family Business and Management",
        "Introductory Probability",
        "Data Analysis and Visualization using Python",
        "Digital Social Sciences",
        "Professional Preparation and Career Avenues in Physical and Sports",
        "Hindi A - B.Com",
        "Hindi B - B.Com",
        "English Language through Literature I"
      ],
    },
  };
  
  export default semesterSubjects;
  